plugins:
  - jekyll-seo-tag #add {% seo %} before </head> in templates

# Stylistic choices
theme: jekyll-theme-minimal

# Site info
title: Mimee Xu
description: Fellow at NYU ILI
phd_topic: Researcher on AI Privacy/Security
phd: PhD NYU Courant 2025
subdescription: Ex-Google, Baidu, Meta, ByteDance
prev_aff: NYU Courant Institute of Mathematical Sciences, Harvey Mudd College, Google Baidu Meta Bytedance UnifyID

logo: /logo.png

markdown: CommonMarkGhPages

# SEO > twitter name meta
twitter:
  username: MimeeXu

x:
  username: MimeeXu

# SEO > site name meta
social:
  name: "Mimee Xu"

# SEO > article author meta
author: MimeeXu

github:
  is_project_page: false
github: [metadata]

docs:

  - title: Home
    url: /
  # title: Publications
  # url: /publications/

  # title: Talks
  # url: /talks/
  
  - title: Research
    url: /bio
  
  - title: Projects
    url: /projects

  - title: About
    url: /contact
# - title: Community
#   url: community
