plugins:
  - jekyll-seo-tag #add {% seo %} before </head> in templates

# Stylistic choices
theme: jekyll-theme-minimal

# Site info
title: mimee.xyz
description: Postdoc at NYU Law, CS PhD on AI Privacy/Security from NYU Courant
subdescription: Mimee Xu

logo: /logo.png

markdown: CommonMarkGhPages

# SEO > twitter name meta
twitter:
  username: MimeeXu

x:
  username: MimeeXu

# SEO > site name meta
social:
  name: "Mimee Xu"

# SEO > article author meta
author: MimeeXu

github:
  is_project_page: false

# docs:
# - title: Bio
#   url: bio

# - title: Research
#   url: research

# - title: Community
#   url: community
